# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_tracing import V1Tracing

class TestV1Tracing(unittest.TestCase):
    """V1Tracing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Tracing:
        """Test V1Tracing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Tracing`
        """
        model = V1Tracing()
        if include_optional:
            return V1Tracing(
                session_id = '',
                trace_id = '',
                span_id = '',
                parent_span_id = ''
            )
        else:
            return V1Tracing(
        )
        """

    def testV1Tracing(self):
        """Test V1Tracing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
