# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_create_multi_llm_chat_completion_request import V1CreateMultiLLMChatCompletionRequest

class TestV1CreateMultiLLMChatCompletionRequest(unittest.TestCase):
    """V1CreateMultiLLMChatCompletionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CreateMultiLLMChatCompletionRequest:
        """Test V1CreateMultiLLMChatCompletionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CreateMultiLLMChatCompletionRequest`
        """
        model = V1CreateMultiLLMChatCompletionRequest()
        if include_optional:
            return V1CreateMultiLLMChatCompletionRequest(
                models = [
                    fixpoint_openapi.models.v1_create_multi_llm_chat_completion_request_model.v1CreateMultiLLMChatCompletionRequestModel(
                        name = '', 
                        temperature = 1.337, 
                        api_key = '', 
                        max_tokens = 56, )
                    ],
                tracing = fixpoint_openapi.models.a_note_on_sessions,_traces,_and_spans:.A note on sessions, traces, and spans:(
                    session_id = '', 
                    trace_id = '', 
                    span_id = '', 
                    parent_span_id = '', ),
                user_id = '',
                messages = [
                    fixpoint_openapi.models.v1_input_message.v1InputMessage(
                        role = '', 
                        content = '', )
                    ],
                mode = 'MODE_UNSPECIFIED'
            )
        else:
            return V1CreateMultiLLMChatCompletionRequest(
        )
        """

    def testV1CreateMultiLLMChatCompletionRequest(self):
        """Test V1CreateMultiLLMChatCompletionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
