# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_tool_call import V1ToolCall

class TestV1ToolCall(unittest.TestCase):
    """V1ToolCall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ToolCall:
        """Test V1ToolCall
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ToolCall`
        """
        model = V1ToolCall()
        if include_optional:
            return V1ToolCall(
                id = '',
                type = '',
                function = fixpoint_openapi.models.tool_call_function.ToolCallFunction(
                    name = '', 
                    arguments = '', )
            )
        else:
            return V1ToolCall(
        )
        """

    def testV1ToolCall(self):
        """Test V1ToolCall"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
