# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_routing_block_type import V1RoutingBlockType

class TestV1RoutingBlockType(unittest.TestCase):
    """V1RoutingBlockType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1RoutingBlockType(self):
        """Test V1RoutingBlockType"""
        # inst = V1RoutingBlockType()

if __name__ == '__main__':
    unittest.main()
