# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_input_message import V1InputMessage

class TestV1InputMessage(unittest.TestCase):
    """V1InputMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1InputMessage:
        """Test V1InputMessage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1InputMessage`
        """
        model = V1InputMessage()
        if include_optional:
            return V1InputMessage(
                role = '',
                content = ''
            )
        else:
            return V1InputMessage(
        )
        """

    def testV1InputMessage(self):
        """Test V1InputMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
