# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_chat_completion_usage import V1ChatCompletionUsage

class TestV1ChatCompletionUsage(unittest.TestCase):
    """V1ChatCompletionUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ChatCompletionUsage:
        """Test V1ChatCompletionUsage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ChatCompletionUsage`
        """
        model = V1ChatCompletionUsage()
        if include_optional:
            return V1ChatCompletionUsage(
                prompt_tokens = 56,
                completion_tokens = 56,
                total_tokens = 56
            )
        else:
            return V1ChatCompletionUsage(
        )
        """

    def testV1ChatCompletionUsage(self):
        """Test V1ChatCompletionUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
