# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_tuning_configuration import V1TuningConfiguration

class TestV1TuningConfiguration(unittest.TestCase):
    """V1TuningConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TuningConfiguration:
        """Test V1TuningConfiguration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TuningConfiguration`
        """
        model = V1TuningConfiguration()
        if include_optional:
            return V1TuningConfiguration(
                secret_alias = '',
                model_name = '',
                hyperparameters = fixpoint_openapi.models.v1_hyperparameters.v1Hyperparameters(
                    epochs = 56, )
            )
        else:
            return V1TuningConfiguration(
        )
        """

    def testV1TuningConfiguration(self):
        """Test V1TuningConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
