# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.fixpoint_update_spending_totals_request import FixpointUpdateSpendingTotalsRequest

class TestFixpointUpdateSpendingTotalsRequest(unittest.TestCase):
    """FixpointUpdateSpendingTotalsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FixpointUpdateSpendingTotalsRequest:
        """Test FixpointUpdateSpendingTotalsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FixpointUpdateSpendingTotalsRequest`
        """
        model = FixpointUpdateSpendingTotalsRequest()
        if include_optional:
            return FixpointUpdateSpendingTotalsRequest(
                models = [
                    fixpoint_openapi.models.fixpointv1_model.fixpointv1Model(
                        provider = '', 
                        name = '', 
                        spend_cap = fixpoint_openapi.models.v1_spend_cap.v1SpendCap(
                            amount = '', 
                            currency = '', 
                            reset_interval = 'RESET_INTERVAL_UNSPECIFIED', ), 
                        usage_totals = fixpoint_openapi.models.v1_usage_totals.v1UsageTotals(
                            amount = '', 
                            currency = '', 
                            tokens_used = 56, 
                            usage_reset_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ]
            )
        else:
            return FixpointUpdateSpendingTotalsRequest(
        )
        """

    def testFixpointUpdateSpendingTotalsRequest(self):
        """Test FixpointUpdateSpendingTotalsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
