# coding: utf-8

"""
    fixpoint/llmproxy/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_output_message import V1OutputMessage

class TestV1OutputMessage(unittest.TestCase):
    """V1OutputMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1OutputMessage:
        """Test V1OutputMessage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1OutputMessage`
        """
        model = V1OutputMessage()
        if include_optional:
            return V1OutputMessage(
                role = '',
                content = '',
                tool_calls = [
                    openapi_client.models.v1_tool_call.v1ToolCall(
                        id = '', 
                        type = '', 
                        function = openapi_client.models.tool_call_function.ToolCallFunction(
                            name = '', 
                            arguments = '', ), )
                    ]
            )
        else:
            return V1OutputMessage(
        )
        """

    def testV1OutputMessage(self):
        """Test V1OutputMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
