# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.tool_call_function import ToolCallFunction

class TestToolCallFunction(unittest.TestCase):
    """ToolCallFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolCallFunction:
        """Test ToolCallFunction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolCallFunction`
        """
        model = ToolCallFunction()
        if include_optional:
            return ToolCallFunction(
                name = '',
                arguments = ''
            )
        else:
            return ToolCallFunction(
        )
        """

    def testToolCallFunction(self):
        """Test ToolCallFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
