# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.routing_block_ab import RoutingBlockAB

class TestRoutingBlockAB(unittest.TestCase):
    """RoutingBlockAB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoutingBlockAB:
        """Test RoutingBlockAB
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoutingBlockAB`
        """
        model = RoutingBlockAB()
        if include_optional:
            return RoutingBlockAB(
                experiment_id = '',
                models = [
                    fixpoint_openapi.models.v1_model.v1Model(
                        name = '', 
                        temperature = 1.337, 
                        api_key = '', 
                        max_tokens = 56, )
                    ]
            )
        else:
            return RoutingBlockAB(
        )
        """

    def testRoutingBlockAB(self):
        """Test RoutingBlockAB"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
