# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_batch_create_fine_tune_jobs_request import V1BatchCreateFineTuneJobsRequest

class TestV1BatchCreateFineTuneJobsRequest(unittest.TestCase):
    """V1BatchCreateFineTuneJobsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BatchCreateFineTuneJobsRequest:
        """Test V1BatchCreateFineTuneJobsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BatchCreateFineTuneJobsRequest`
        """
        model = V1BatchCreateFineTuneJobsRequest()
        if include_optional:
            return V1BatchCreateFineTuneJobsRequest(
                dataset_id = '',
                tuning_configs = [
                    fixpoint_openapi.models.v1_tuning_configuration.v1TuningConfiguration(
                        secret_alias = '', 
                        model_name = '', 
                        hyperparameters = fixpoint_openapi.models.v1_hyperparameters.v1Hyperparameters(
                            epochs = 56, ), )
                    ],
                mode = 'MODE_UNSPECIFIED'
            )
        else:
            return V1BatchCreateFineTuneJobsRequest(
        )
        """

    def testV1BatchCreateFineTuneJobsRequest(self):
        """Test V1BatchCreateFineTuneJobsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
