# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_create_multi_llm_chat_completion_request_model import V1CreateMultiLLMChatCompletionRequestModel

class TestV1CreateMultiLLMChatCompletionRequestModel(unittest.TestCase):
    """V1CreateMultiLLMChatCompletionRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CreateMultiLLMChatCompletionRequestModel:
        """Test V1CreateMultiLLMChatCompletionRequestModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CreateMultiLLMChatCompletionRequestModel`
        """
        model = V1CreateMultiLLMChatCompletionRequestModel()
        if include_optional:
            return V1CreateMultiLLMChatCompletionRequestModel(
                name = '',
                temperature = 1.337,
                api_key = '',
                max_tokens = 56
            )
        else:
            return V1CreateMultiLLMChatCompletionRequestModel(
        )
        """

    def testV1CreateMultiLLMChatCompletionRequestModel(self):
        """Test V1CreateMultiLLMChatCompletionRequestModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
