# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.fixpoint_create_open_ai_chat_output_log_request import FixpointCreateOpenAIChatOutputLogRequest

class TestFixpointCreateOpenAIChatOutputLogRequest(unittest.TestCase):
    """FixpointCreateOpenAIChatOutputLogRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FixpointCreateOpenAIChatOutputLogRequest:
        """Test FixpointCreateOpenAIChatOutputLogRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FixpointCreateOpenAIChatOutputLogRequest`
        """
        model = FixpointCreateOpenAIChatOutputLogRequest()
        if include_optional:
            return FixpointCreateOpenAIChatOutputLogRequest(
                input_name = '',
                openai_id = '',
                session_name = '',
                trace_id = '',
                mode = 'MODE_UNSPECIFIED',
                choices = [
                    fixpoint_openapi.models.v1_open_ai_chat_output_log_choice.v1OpenAIChatOutputLogChoice(
                        index = '', 
                        message = fixpoint_openapi.models.v1_output_message.v1OutputMessage(
                            role = '', 
                            content = '', 
                            tool_calls = [
                                fixpoint_openapi.models.v1_tool_call.v1ToolCall(
                                    id = '', 
                                    type = '', 
                                    function = fixpoint_openapi.models.tool_call_function.ToolCallFunction(
                                        name = '', 
                                        arguments = '', ), )
                                ], ), 
                        finish_reason = '', )
                    ],
                usage = fixpoint_openapi.models.v1_open_ai_chat_output_log_usage.v1OpenAIChatOutputLogUsage(
                    prompt_tokens = 56, 
                    completion_tokens = 56, 
                    total_tokens = 56, )
            )
        else:
            return FixpointCreateOpenAIChatOutputLogRequest(
        )
        """

    def testFixpointCreateOpenAIChatOutputLogRequest(self):
        """Test FixpointCreateOpenAIChatOutputLogRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
