# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.v1_list_fine_tune_jobs_response import V1ListFineTuneJobsResponse

class TestV1ListFineTuneJobsResponse(unittest.TestCase):
    """V1ListFineTuneJobsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ListFineTuneJobsResponse:
        """Test V1ListFineTuneJobsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ListFineTuneJobsResponse`
        """
        model = V1ListFineTuneJobsResponse()
        if include_optional:
            return V1ListFineTuneJobsResponse(
                fine_tune_jobs = [
                    fixpoint_openapi.models.v1_fine_tune_job.v1FineTuneJob(
                        id = '', 
                        set_id = '', 
                        dataset_id = '', 
                        model_name = '', 
                        status = 'FINE_TUNE_STATUS_UNSPECIFIED', 
                        hyperparameters = fixpoint_openapi.models.v1_hyperparameters.v1Hyperparameters(
                            epochs = 56, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        secret_alias = '', 
                        fine_tuned_model = '', 
                        provider_job_id = '', 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return V1ListFineTuneJobsResponse(
        )
        """

    def testV1ListFineTuneJobsResponse(self):
        """Test V1ListFineTuneJobsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
