# coding: utf-8

"""
    fixpoint/v1/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fixpoint_openapi.models.fixpointv1_spend_cap import Fixpointv1SpendCap

class TestFixpointv1SpendCap(unittest.TestCase):
    """Fixpointv1SpendCap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Fixpointv1SpendCap:
        """Test Fixpointv1SpendCap
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Fixpointv1SpendCap`
        """
        model = Fixpointv1SpendCap()
        if include_optional:
            return Fixpointv1SpendCap(
                amount = '',
                currency = '',
                reset_interval = 'RESET_INTERVAL_UNSPECIFIED'
            )
        else:
            return Fixpointv1SpendCap(
        )
        """

    def testFixpointv1SpendCap(self):
        """Test Fixpointv1SpendCap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
