name: Release PyPi test package

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
          cache-dependency-path: ${{ github.workspace }}/requirements.txt

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
        working-directory: ${{ github.workspace }}

      - name: Build package
        run: poetry build
        working-directory: ${{ github.workspace }}

      - name: configure Poetry repo
        run: poetry config repositories.testpypi https://test.pypi.org/simple/

      - name: configure Poetry PyPi token
        run: poetry config pypi-token.test-pypi ${{ secrets.PYPI_API_TOKEN_TEST }}

      - name: Publish to PyPI test repository
        run: poetry publish --no-interaction --repository testpypi
        working-directory: ${{ github.workspace }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_TEST }}
